import { addDays, format } from "date-fns";
import type {
  BusinessSettings,
  Program,
  SessionType,
  SessionWithRelations,
  Trainer,
  Review,
} from "@/lib/types/database";
import { SITE } from "@/lib/constants";

/** Local fallback content when Supabase is not configured. Marked as SAMPLE. */

export const FALLBACK_PROGRAMS: Program[] = [
  {
    id: "prog-little",
    name: "Little Dawgs",
    slug: "little-dawgs",
    short_description:
      "For younger athletes learning proper movement, balance, coordination, speed, and body control in a positive environment.",
    full_description:
      "Little Dawgs introduces foundational athletic skills through fun, age-appropriate drills. Athletes build confidence while developing movement quality in a supportive group setting.",
    minimum_age: 5,
    maximum_age: 10,
    default_duration_minutes: 45,
    default_capacity: 10,
    default_price: 25,
    image_url: "/images/dawg/programs/little-dawgs.svg",
    active: true,
    featured: true,
    display_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "prog-big",
    name: "Big Dawgs",
    slug: "big-dawgs",
    short_description:
      "Advanced athletic development for older youth athletes — strength, speed, agility, conditioning, and competitive movement.",
    full_description:
      "Big Dawgs challenges older athletes with progressive strength, speed, and agility training designed to transfer to their sport.",
    minimum_age: 11,
    maximum_age: 18,
    default_duration_minutes: 60,
    default_capacity: 12,
    default_price: 30,
    image_url: "/images/dawg/programs/big-dawgs.svg",
    active: true,
    featured: true,
    display_order: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "prog-private",
    name: "Private Training",
    slug: "private-training",
    short_description:
      "Individualized instruction based on the athlete’s age, sport, experience, and development goals.",
    full_description:
      "One-on-one sessions with customized plans for speed, strength, agility, or sport-specific performance.",
    minimum_age: 5,
    maximum_age: 18,
    default_duration_minutes: 60,
    default_capacity: 1,
    default_price: 60,
    image_url: "/images/dawg/programs/private.svg",
    active: true,
    featured: true,
    display_order: 3,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "prog-small",
    name: "Small-Group Training",
    slug: "small-group-training",
    short_description:
      "Focused instruction for siblings, teammates, or small groups who want to train together.",
    full_description:
      "Small-group sessions keep coaching attention high while building teamwork and competitive energy.",
    minimum_age: 7,
    maximum_age: 18,
    default_duration_minutes: 60,
    default_capacity: 4,
    default_price: 40,
    image_url: "/images/dawg/programs/small-group.svg",
    active: true,
    featured: true,
    display_order: 4,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const FALLBACK_SESSION_TYPES: SessionType[] = [
  { id: "st-group", name: "Group Class", slug: "group-class", active: true },
  { id: "st-private", name: "Private Lesson", slug: "private-lesson", active: true },
  { id: "st-small", name: "Small-Group Lesson", slug: "small-group-lesson", active: true },
  { id: "st-camp", name: "Camp", slug: "camp", active: true },
  { id: "st-clinic", name: "Clinic", slug: "clinic", active: true },
];

export const FALLBACK_TRAINERS: Trainer[] = [
  {
    id: "trainer-1",
    profile_id: null,
    name: "Coach Avery",
    title: "Owner / Head Trainer",
    bio: "DAWG specifically emphasizes developing both physical and mental attributes in athletes within a positive and engaging setting.",
    photo_url: "/images/dawg/trainers/placeholder.svg",
    specialties: ["Speed", "Agility", "Youth Athletic Development"],
    certifications: [],
    coaching_experience: "Youth athletic training in Mooresville, Indiana",
    sports_background: "Sports performance coaching",
    active: true,
    display_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

function sampleDate(daysAhead: number): string {
  return format(addDays(new Date(), daysAhead), "yyyy-MM-dd");
}

export const FALLBACK_SESSIONS: SessionWithRelations[] = [
  {
    id: "sess-1",
    program_id: "prog-little",
    session_type_id: "st-group",
    trainer_id: "trainer-1",
    title: "[SAMPLE] Little Dawgs Speed & Agility",
    description: "Sample session for development — replace before launch.",
    session_date: sampleDate(3),
    start_time: "16:00:00",
    end_time: "16:45:00",
    timezone: SITE.timezone,
    minimum_age: 5,
    maximum_age: 10,
    skill_level: "Beginner",
    capacity: 10,
    price: 25,
    deposit_amount: null,
    payment_requirement: "pay_at_facility",
    location_name: SITE.name,
    location_address: SITE.address.full,
    what_to_bring: "Athletic shoes, water bottle, comfortable training clothes",
    cancellation_policy: "Please cancel at least 24 hours in advance when possible.",
    status: "published",
    featured: true,
    published_at: new Date().toISOString(),
    recurrence_group_id: null,
    created_by: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    program: FALLBACK_PROGRAMS[0],
    session_type: FALLBACK_SESSION_TYPES[0],
    trainer: FALLBACK_TRAINERS[0],
    booked_count: 7,
    spots_remaining: 3,
  },
  {
    id: "sess-2",
    program_id: "prog-big",
    session_type_id: "st-group",
    trainer_id: "trainer-1",
    title: "[SAMPLE] Big Dawgs Strength & Speed",
    description: "Sample session for development — replace before launch.",
    session_date: sampleDate(4),
    start_time: "17:00:00",
    end_time: "18:00:00",
    timezone: SITE.timezone,
    minimum_age: 11,
    maximum_age: 18,
    skill_level: "Intermediate",
    capacity: 12,
    price: 30,
    deposit_amount: null,
    payment_requirement: "pay_at_facility",
    location_name: SITE.name,
    location_address: SITE.address.full,
    what_to_bring: "Athletic shoes, water bottle, comfortable training clothes",
    cancellation_policy: "Please cancel at least 24 hours in advance when possible.",
    status: "published",
    featured: false,
    published_at: new Date().toISOString(),
    recurrence_group_id: null,
    created_by: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    program: FALLBACK_PROGRAMS[1],
    session_type: FALLBACK_SESSION_TYPES[0],
    trainer: FALLBACK_TRAINERS[0],
    booked_count: 4,
    spots_remaining: 8,
  },
  {
    id: "sess-3",
    program_id: "prog-private",
    session_type_id: "st-private",
    trainer_id: "trainer-1",
    title: "[SAMPLE] Private Training — Speed Focus",
    description: "Sample private lesson slot — replace before launch.",
    session_date: sampleDate(5),
    start_time: "15:00:00",
    end_time: "16:00:00",
    timezone: SITE.timezone,
    minimum_age: 7,
    maximum_age: 18,
    skill_level: "All levels",
    capacity: 1,
    price: 60,
    deposit_amount: null,
    payment_requirement: "pay_at_facility",
    location_name: SITE.name,
    location_address: SITE.address.full,
    what_to_bring: "Athletic shoes, water bottle",
    cancellation_policy: "Please cancel at least 24 hours in advance when possible.",
    status: "published",
    featured: false,
    published_at: new Date().toISOString(),
    recurrence_group_id: null,
    created_by: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    program: FALLBACK_PROGRAMS[2],
    session_type: FALLBACK_SESSION_TYPES[1],
    trainer: FALLBACK_TRAINERS[0],
    booked_count: 0,
    spots_remaining: 1,
  },
  {
    id: "sess-4",
    program_id: "prog-small",
    session_type_id: "st-small",
    trainer_id: "trainer-1",
    title: "[SAMPLE] Small-Group Agility",
    description: "Sample small-group session — replace before launch.",
    session_date: sampleDate(6),
    start_time: "16:30:00",
    end_time: "17:30:00",
    timezone: SITE.timezone,
    minimum_age: 8,
    maximum_age: 14,
    skill_level: "All levels",
    capacity: 4,
    price: 40,
    deposit_amount: null,
    payment_requirement: "pay_at_facility",
    location_name: SITE.name,
    location_address: SITE.address.full,
    what_to_bring: "Athletic shoes, water bottle",
    cancellation_policy: "Please cancel at least 24 hours in advance when possible.",
    status: "published",
    featured: false,
    published_at: new Date().toISOString(),
    recurrence_group_id: null,
    created_by: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    program: FALLBACK_PROGRAMS[3],
    session_type: FALLBACK_SESSION_TYPES[2],
    trainer: FALLBACK_TRAINERS[0],
    booked_count: 2,
    spots_remaining: 2,
  },
  {
    id: "sess-5",
    program_id: "prog-little",
    session_type_id: "st-group",
    trainer_id: "trainer-1",
    title: "[SAMPLE] Little Dawgs Movement Foundations",
    description: "Sample session for development — replace before launch.",
    session_date: sampleDate(8),
    start_time: "16:00:00",
    end_time: "16:45:00",
    timezone: SITE.timezone,
    minimum_age: 5,
    maximum_age: 10,
    skill_level: "Beginner",
    capacity: 10,
    price: 25,
    deposit_amount: null,
    payment_requirement: "pay_at_facility",
    location_name: SITE.name,
    location_address: SITE.address.full,
    what_to_bring: "Athletic shoes, water bottle",
    cancellation_policy: "Please cancel at least 24 hours in advance when possible.",
    status: "published",
    featured: false,
    published_at: new Date().toISOString(),
    recurrence_group_id: null,
    created_by: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    program: FALLBACK_PROGRAMS[0],
    session_type: FALLBACK_SESSION_TYPES[0],
    trainer: FALLBACK_TRAINERS[0],
    booked_count: 1,
    spots_remaining: 9,
  },
  {
    id: "sess-6",
    program_id: "prog-big",
    session_type_id: "st-group",
    trainer_id: "trainer-1",
    title: "[SAMPLE] Big Dawgs Conditioning",
    description: "Sample session for development — replace before launch.",
    session_date: sampleDate(10),
    start_time: "17:00:00",
    end_time: "18:00:00",
    timezone: SITE.timezone,
    minimum_age: 11,
    maximum_age: 18,
    skill_level: "Intermediate",
    capacity: 12,
    price: 30,
    deposit_amount: null,
    payment_requirement: "pay_at_facility",
    location_name: SITE.name,
    location_address: SITE.address.full,
    what_to_bring: "Athletic shoes, water bottle",
    cancellation_policy: "Please cancel at least 24 hours in advance when possible.",
    status: "published",
    featured: false,
    published_at: new Date().toISOString(),
    recurrence_group_id: null,
    created_by: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    program: FALLBACK_PROGRAMS[1],
    session_type: FALLBACK_SESSION_TYPES[0],
    trainer: FALLBACK_TRAINERS[0],
    booked_count: 12,
    spots_remaining: 0,
  },
];

export const FALLBACK_REVIEWS: Review[] = [];

export const FALLBACK_SETTINGS: BusinessSettings = {
  id: "settings-1",
  business_name: SITE.name,
  phone: SITE.phone,
  email: SITE.email,
  address_line_1: SITE.address.line1,
  address_line_2: null,
  city: SITE.address.city,
  state: SITE.address.state,
  postal_code: SITE.address.postalCode,
  map_embed_url: SITE.mapEmbedUrl,
  facebook_url: SITE.facebookUrl,
  business_hours: SITE.hoursPlaceholder,
  homepage_announcement: null,
  cancellation_policy:
    "Please cancel at least 24 hours in advance when possible. Contact DAWG to reschedule.",
  booking_policy:
    "Reservations hold your athlete’s spot. Payment is due at the facility unless otherwise noted. Parent or legal guardian must book for minors.",
  updated_at: new Date().toISOString(),
};
