import { addDays, format } from "date-fns";
import type {
  BusinessSettings,
  Program,
  SessionType,
  SessionWithRelations,
  Trainer,
  Review,
} from "@/lib/types/database";
import { SITE } from "@/lib/constants";

/** Local fallback content when Supabase is not configured. Marked as SAMPLE. */

export const FALLBACK_PROGRAMS: Program[] = [
  {
    id: "prog-little",
    name: "Little Dawgs",
    slug: "little-dawgs",
    short_description:
      "For younger athletes learning proper movement, balance, coordination, speed, and body control in a positive environment.",
    full_description:
      "Little Dawgs introduces foundational athletic skills through fun, age-appropriate drills. Athletes build confidence while developing movement quality in a supportive group setting.",
    minimum_age: 5,
    maximum_age: 10,
    default_duration_minutes: 45,
    default_capacity: 10,
    default_price_cents: 2500,
    image_url: "/images/dawg/programs/little-dawgs.jpg",
    active: true,
    featured: true,
    display_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "prog-big",
    name: "Big Dawgs",
    slug: "big-dawgs",
    short_description:
      "Advanced athletic development for older youth athletes — strength, speed, agility, conditioning, and competitive movement.",
    full_description:
      "Big Dawgs challenges older athletes with progressive strength, speed, and agility training designed to transfer to their sport.",
    minimum_age: 11,
    maximum_age: 18,
    default_duration_minutes: 60,
    default_capacity: 12,
    default_price_cents: 3000,
    image_url: "/images/dawg/programs/big-dawgs.jpg",
    active: true,
    featured: true,
    display_order: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const FALLBACK_SESSION_TYPES: SessionType[] = [
  { id: "st-group", name: "Group Class", slug: "group-class", active: true },
  { id: "st-private", name: "Private Lesson", slug: "private-lesson", active: true },
  { id: "st-small", name: "Small-Group Lesson", slug: "small-group-lesson", active: true },
  { id: "st-camp", name: "Camp", slug: "camp", active: true },
  { id: "st-clinic", name: "Clinic", slug: "clinic", active: true },
];

export const FALLBACK_TRAINERS: Trainer[] = [
  {
    id: "trainer-1",
    profile_id: null,
    name: "Coach Avery",
    title: "Owner / Head Trainer",
    bio: "DAWG specifically emphasizes developing both physical and mental attributes in athletes within a positive and engaging setting.",
    photo_url: "/images/dawg/trainers/avery.jpg",
    specialties: ["Speed", "Agility", "Youth Athletic Development"],
    certifications: [],
    coaching_experience: "Youth athletic training in Mooresville, Indiana",
    sports_background: "Sports performance coaching",
    active: true,
    display_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

function sampleDate(daysAhead: number): string {
  return format(addDays(new Date(), daysAhead), "yyyy-MM-dd");
}

export const FALLBACK_SESSIONS: SessionWithRelations[] = [
  {
    id: "sess-1",
    program_id: "prog-little",
    session_type_id: "st-group",
    trainer_id: "trainer-1",
    title: "Little Dawgs Speed & Agility",
    description: "Age-appropriate athletic training at DAWG Youth Training.",
    session_date: sampleDate(3),
    start_time: "16:00:00",
    end_time: "16:45:00",
    timezone: SITE.timezone,
    minimum_age: 5,
    maximum_age: 10,
    skill_level: "Beginner",
    capacity: 10,
    price_cents: 2500,
    currency: "usd",
    deposit_amount_cents: null,
    payment_requirement: "online_or_facility",
    location_name: SITE.name,
    location_address: SITE.address.full,
    what_to_bring: "Athletic shoes, water bottle, comfortable training clothes",
    cancellation_policy: "Please cancel at least 24 hours in advance when possible.",
    status: "published",
    featured: true,
    published_at: new Date().toISOString(),
    recurrence_group_id: null,
    created_by: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    program: FALLBACK_PROGRAMS[0],
    session_type: FALLBACK_SESSION_TYPES[0],
    trainer: FALLBACK_TRAINERS[0],
    booked_count: 7,
    spots_remaining: 3,
  },
  {
    id: "sess-2",
    program_id: "prog-big",
    session_type_id: "st-group",
    trainer_id: "trainer-1",
    title: "Big Dawgs Strength & Speed",
    description: "Age-appropriate athletic training at DAWG Youth Training.",
    session_date: sampleDate(4),
    start_time: "17:00:00",
    end_time: "18:00:00",
    timezone: SITE.timezone,
    minimum_age: 11,
    maximum_age: 18,
    skill_level: "Intermediate",
    capacity: 12,
    price_cents: 3000,
    currency: "usd",
    deposit_amount_cents: null,
    payment_requirement: "pay_online",
    location_name: SITE.name,
    location_address: SITE.address.full,
    what_to_bring: "Athletic shoes, water bottle, comfortable training clothes",
    cancellation_policy: "Please cancel at least 24 hours in advance when possible.",
    status: "published",
    featured: false,
    published_at: new Date().toISOString(),
    recurrence_group_id: null,
    created_by: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    program: FALLBACK_PROGRAMS[1],
    session_type: FALLBACK_SESSION_TYPES[0],
    trainer: FALLBACK_TRAINERS[0],
    booked_count: 4,
    spots_remaining: 8,
  },
  {
    id: "sess-5",
    program_id: "prog-little",
    session_type_id: "st-group",
    trainer_id: "trainer-1",
    title: "Little Dawgs Movement Foundations",
    description: "Age-appropriate athletic training at DAWG Youth Training.",
    session_date: sampleDate(8),
    start_time: "16:00:00",
    end_time: "16:45:00",
    timezone: SITE.timezone,
    minimum_age: 5,
    maximum_age: 10,
    skill_level: "Beginner",
    capacity: 10,
    price_cents: 2500,
    currency: "usd",
    deposit_amount_cents: null,
    payment_requirement: "online_or_facility",
    location_name: SITE.name,
    location_address: SITE.address.full,
    what_to_bring: "Athletic shoes, water bottle",
    cancellation_policy: "Please cancel at least 24 hours in advance when possible.",
    status: "published",
    featured: false,
    published_at: new Date().toISOString(),
    recurrence_group_id: null,
    created_by: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    program: FALLBACK_PROGRAMS[0],
    session_type: FALLBACK_SESSION_TYPES[0],
    trainer: FALLBACK_TRAINERS[0],
    booked_count: 1,
    spots_remaining: 9,
  },
  {
    id: "sess-6",
    program_id: "prog-big",
    session_type_id: "st-group",
    trainer_id: "trainer-1",
    title: "Big Dawgs Conditioning",
    description: "Age-appropriate athletic training at DAWG Youth Training.",
    session_date: sampleDate(10),
    start_time: "17:00:00",
    end_time: "18:00:00",
    timezone: SITE.timezone,
    minimum_age: 11,
    maximum_age: 18,
    skill_level: "Intermediate",
    capacity: 12,
    price_cents: 3000,
    currency: "usd",
    deposit_amount_cents: null,
    payment_requirement: "online_or_facility",
    location_name: SITE.name,
    location_address: SITE.address.full,
    what_to_bring: "Athletic shoes, water bottle",
    cancellation_policy: "Please cancel at least 24 hours in advance when possible.",
    status: "published",
    featured: false,
    published_at: new Date().toISOString(),
    recurrence_group_id: null,
    created_by: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    program: FALLBACK_PROGRAMS[1],
    session_type: FALLBACK_SESSION_TYPES[0],
    trainer: FALLBACK_TRAINERS[0],
    booked_count: 12,
    spots_remaining: 0,
  },
];

export const FALLBACK_REVIEWS: Review[] = [
  {
    id: "review-brad",
    reviewer_name: "Brad Allen",
    reviewer_description: "Parent · Facebook review",
    athlete_sport: null,
    rating: 5,
    review_text:
      "Working with Coach Avery is a true blessing. My boys have been going to the Dawgs house for a little over 6 months and their transformation is incredible. Not only are they stronger and more agile but their confidence in themselves is skyrocketing!",
    published: true,
    featured: true,
    display_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "review-2",
    reviewer_name: "Jessica M.",
    reviewer_description: "Parent of a youth athlete",
    athlete_sport: null,
    rating: 5,
    review_text:
      "My daughter looks forward to every session. The coaching is positive, the workouts are challenging, and we’ve seen real gains in her speed and confidence on the field.",
    published: true,
    featured: true,
    display_order: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "review-3",
    reviewer_name: "Marcus T.",
    reviewer_description: "Parent · Big Dawgs",
    athlete_sport: "Football",
    rating: 5,
    review_text:
      "DAWG has been a game changer for my son. Better movement, stronger legs, and a mindset that shows up in practice and games. Coach Avery knows how to push kids the right way.",
    published: true,
    featured: true,
    display_order: 3,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "review-4",
    reviewer_name: "Amanda R.",
    reviewer_description: "Parent of a Little Dawgs",
    athlete_sport: null,
    rating: 5,
    review_text:
      "Perfect environment for younger athletes. Fun, structured, and encouraging — my kids leave sweaty, smiling, and proud of what they worked on.",
    published: true,
    featured: false,
    display_order: 4,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "review-5",
    reviewer_name: "Chris D.",
    reviewer_description: "Parent · Private training",
    athlete_sport: "Basketball",
    rating: 5,
    review_text:
      "One-on-one training helped my athlete fix bad habits and build explosive movement. Clear coaching, great energy, and results you can see.",
    published: true,
    featured: false,
    display_order: 5,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const FALLBACK_SETTINGS: BusinessSettings = {
  id: "settings-1",
  business_name: SITE.name,
  phone: SITE.phone,
  email: SITE.email,
  address_line_1: SITE.address.line1,
  address_line_2: null,
  city: SITE.address.city,
  state: SITE.address.state,
  postal_code: SITE.address.postalCode,
  map_embed_url: SITE.mapEmbedUrl,
  facebook_url: SITE.facebookUrl,
  business_hours: SITE.hoursPlaceholder,
  homepage_announcement: null,
  cancellation_policy:
    "Please cancel at least 24 hours in advance when possible. Contact DAWG to reschedule.",
  booking_policy:
    "Reservations hold your athlete’s spot. Payment is due at the facility unless otherwise noted. Parent or legal guardian must book for minors.",
  updated_at: new Date().toISOString(),
};
